main: ${project.main}
name: ${project.name}
version: ${project.version}
authors: ${project.authors}
depend: ${project.dependencies}
permissions:
  redischat.admin:
    default: op
  redischat.command.channel:
    default: true
  redischat.command.msg:
    default: true
  redischat.command.reply:
    default: true
  redischat.command.channel.set.password:
    default: true
  redischat.command.set.listed:
    default: true
  redischat.command.set.radius:
     default: true
  redischat.command.channel.set.textcolor:
     default: true
  redischat.command.channel.set.namecolor:
     default: true

commands:
  channel:
    aliases: [chan]
    permission: redischat.command.channel
  msg:
    aliases: [tell, whisper, pm]
    permission: redischat.command.msg
  reply:
    aliases: [r]
    permission: redischat.command.reply
  chat:
    permission: redischat.command.chat